#!/bin/bash

reference=${1:?no reference build number given}

diff -u0 <(show_bad_projects $reference) <(show_bad_projects $2) \
    | egrep -v '^(@@|---|\+\+\+)' \
    | sed 's/^-For/---For/' \
    | sed 's/^+For/+++For/' \
    | colordiff
